### ISSUE TITLE
Can't commit with vim editor

### ISSUE THREAD

**Issue by edgimar** [Alcaro/GitBSLR#1]
When I try to commit to a repository, I get the following error:

    GitBSLR: internal error, unexpected absolute path /usr/bin/python3
    error: There was a problem with the editor 'vim'.
    Please supply the message using either -m or -F option.

This appears to have something to do with vim using python3 in the vimrc file.  Any ideas on how to fix this?  Of course I can commit using /usr/bin/git, but it would be ideal if I could use the bash alias that uses GitBSLR.

If interested, the part of my vimrc that seems to cause the problem looks like this:

```vim
" Add the python path to the VIM search path so VIM can find library files {{{
" with the "gf" command
python3 << EOF
import os
import sys
import vim
for p in sys.path:
    # Add each directory in sys.path, if it exists.
    if os.path.isdir(p):
        # Command 'set' needs backslash before each space.
        vim.command(r"set path+=%s" % (p.replace(" ", r"\ ")))
EOF
```

**Comment by BrettRyland** [comment]
I get a similar problem:
```
hint: Waiting for your editor to close the file... GitBSLR: internal error, unexpected absolute path /proc/self/exe
error: There was a problem with the editor 'vim'.
```
though I don't see anything in my .vimrc that would cause this.

**Comment by Alcaro** [comment]
ugh, why does github not subscribe me to my own repos...

Yep, that's a bug, I forgot environment variables are inherited by child processes, like the EDITOR. GitBSLR doesn't like being loaded into anything except Git.

Easy fix.
