### ISSUE TITLE
Another Git is in front of the wrapper

### ISSUE THREAD

**Issue by f-liva** [Alcaro/GitBSLR#10]
After running install.sh I got this warning

`warning: installed to /home/forge/bin/git, but /home/forge/bin/ is not in your PATH (or another Git is in front of /home/forge/bin/); fix that to complete the installation`

My git is located in **/usr/bin/git** and the script in /home/forge/bin/git correcly use the default git:

```bash
#!/bin/sh
export LD_PRELOAD=/home/forge/bin/gitbslr.so
exec /usr/bin/git "$@"
```
But how can I use YOUR git wrapper when I hust call **git** from console?

**Comment by f-liva** [comment]
For everybody had my problem, the fix is simple:

```bash
export PATH="$HOME/bin:$PATH"
```

Read https://linuxize.com/post/how-to-add-directory-to-path-in-linux/

**Comment by Alcaro** [comment]
~/bin is usually added to PATH by your shell, but only if it exists already. install.sh is happy to create it, but if it does, PATH won't be set until you restart your terminal.

I should make it check for that. And I should make it print proper instructions, rather than 'fix that'.

**Comment by f-liva** [comment]
Thank you! Awesome project, anyway, thank you a lot!
