### ISSUE TITLE
Problem while cloning a Git repository

### ISSUE THREAD

**Issue by francoisthire** [Alcaro/GitBSLR#11]
While cloning the following git repository `https://gitlab.com/tezos/tezos.git` I get some errors related to symlinks. For example, one problematic file is the following one: `https://gitlab.com/tezos/tezos/blob/master/.github/ISSUE_TEMPLATE.md`. Without `GitBSLR` there is no issue.

**Comment by Alcaro** [comment]
Yep, that's a bug. Fixed, thanks for reporting.
