### ISSUE TITLE
.gitignore

### ISSUE THREAD

**Issue by DavidEBrumbaugh** [Alcaro/GitBSLR#12]
I have installed GitBSLR 

I don't know if this is a bug/feature or if I'm not using it correctly.

I cloned a repo, moved the image directory and created a symlink to that directory.
There's a line in the .gitignore image/cache 

When I run git status, it lists the files in image/cache as "modified"

And advice would be greatly appreciated!

**Comment by Alcaro** [comment]
gitignore only prevents files from being committed. If they're in the repo, Git will track updates and deletions, even if the file is in gitignore.

If you want to delete or rename that directory, and want Git to leave it alone, maybe you want git update-index --assume-unchanged. If you think it's a GitBSLR bug, provide exact reproduction steps; as far as I can see, gitignore works across symlinks.

**Comment by DavidEBrumbaugh** [comment]
I'm no longer convinced it's a bug.  I actually came in here to delete my comment.  But since you responded I won't (thanks BTW!) ...  I'm going to close this for now, and open it again if something changes.

Thank you again (very much!) for responding so quickly.
