### ISSUE TITLE
Breakes git in submodules

### ISSUE THREAD

**Issue by Emily3403** [Alcaro/GitBSLR#16]
When adding an arbitrary submodule in a git directory, one cannot commit any files or show the status.
To reproduce (in an empty directory):
```
git init
git submodule add https://github.com/Alcaro/GitBSLR
git status
```
Now the output is `GitBSLR: unexpected access to /home; should only be in /home/emily/Desktop/testing/ or /home/emily/Desktop/testing/.git/. Either you're missing GITBSLR_GIT_DIR and/or GITBSLR_WORK_TREE, or you found a GitBSLR bug. If latter, please report it: https://github.com/Alcaro/GitBSLR/issues`.

When setting `$GITBSLR_GIT_DIR` to the correct path with `export GITBSLR_GIT_DIR=$PWD/.git` the bug still appears.

**Comment by Alcaro** [comment]
Your reproduction step lacks a cd GitBSLR step, but I can reproduce the issue if I add that. For some reason, git lstats /home/alcaro/z/git/GitBSLR, and every parent thereof, except /. No idea why, but it should be an easy fix.

GitBSLR also detects git dir /home/alcaro/z/git/GitBSLR/../.git/, which is its own bug - that ../ component looks like trouble.

**Comment by Alcaro** [comment]
...that was more git weirdness and GitBSLR bugs than I expected. Fixed everything I could find, but Git is weird, so I may have missed a few. Please test.

**Comment by ghost** [comment]
Seems to work on all my git repositories. Thanks alot for the quick fix ^^
