### ISSUE TITLE
Breaks when symlinking to another git repo

### ISSUE THREAD

**Issue by Emily3403** [Alcaro/GitBSLR#17]
When the symlink contains a git repository the error message 
```
error: invalid path 'a/'
error: unable to add 'a/' to index
fatal: adding files failed
```
arises.

To test this behaviour create two git repositories and symlink 1 into the other.
```
cd /tmp
mkdir a && cd a && git init
cd ..
mkdir b && cd b && git init
ln -s ../a .
git add a
```
Now the error arises.

**Comment by Alcaro** [comment]
Vanilla Git also does weird things if you stick repos in each other. I don't know enough about Git to determine what it's supposed to do.

But I can determine it's not supposed to give different errors between vanilla Git and GitBSLR.

I hope the idea of having multiple .git directories in the same Git invocation won't break anything too badly...

**Comment by ghost** [comment]
It seams to work now. Thanks a lot!
