### ISSUE TITLE
Follow links only on specified branch

### ISSUE THREAD

**Issue by epcim** [Alcaro/GitBSLR#2]
Hi, nice idea you have had. I would have one suggestion, frequently you still want at least one branch to contain symlinks (so "bob" can clone "alice" repo and use it the same way), so would be nice to only follow links for files on "master" while on "develop" you would keep them all. However such bit prevent merging strategies, etc..

0.02c tip - instead of install.sh suggest, just use allias in the repo directory, with https://github.com/direnv/direnv you can have .envrc in a repo, that will only alias, git command in this repository.

**Comment by Alcaro** [comment]
> frequently you still want at least one branch to contain symlinks

Are you saying
- there's a directory shared between a Git repo and something else (possibly another Git repo)
- there are multiple versions of the directory on different branches
- you want the outside directory to always point to master, even if you switch the repo to another branch
- and you can't find how to tell GitBSLR to do that?

If yes, not a bad idea. I think the best way to do that would be having one shared-master directory and one shared-develop directory, both outside the repo, a symlink inside the repo that points to one of them, and a hook on 'git branch' that changes where the symlink points.

If you're thinking of something else, please clarify. GitBSLR can't autoconfigure the symlinks, Git only sees normal directories and that's what gets pushed to GitHub.

> with https://github.com/direnv/direnv you can have .envrc in a repo, that will only alias, git command in this repository.

Interesting idea. Unfortunately, it won't work here: direnv supports [environment variables only](https://github.com/direnv/direnv/blob/master/README.md#common-things-people-dont-know), no aliases or functions.

Non-global GitBSLR installations may be a security risk too (you don't want vanilla Git to create a symlink to /home/epcim, and GitBSLR to follow it and create a .bashrc). Malicious repos usually have easier ways to break your system, so that may not be a major concern, but I'm not comfortable recommending it.

**Comment by gcarabetta** [comment]
Hi! I'm new about git, and I've just got the "is beyond a symbolic link" error.
I found this, but I tryed it and seems is not working for me.

I'm on a Rapsberry:
root@raspberrypi:~ # cat /etc/issue
Raspbian GNU/Linux 9 \n \l
root@raspberrypi:~ # uname -a
Linux raspberrypi 4.14.34-v7+ #1110 SMP Mon Apr 16 15:18:51 BST 2018 armv7l GNU/Linux

I did: 
apt-get dist-upgrade
apt-get install git
cd /
git init
git add /usr/local
---> ok
git add /var/www/html/SITE1/user/init.php
--> error ( html is a symlink to /var/www/html.ver.12/ )

downloaded GitBSLR, make OPT=1, cp gitbslr.so /lib
alias  git="LD_PRELOAD='/lib/gitbslr.so'  git"
git add /var/www/html/SITE1/user/init.php

and I got the same error.

Can you help me?
Thanks

**Comment by Alcaro** [comment]
(Better create a new issue than post in an irrelevant one.)

Using the root directory as a git repo... well, that's an interesting method. Seems dangerous, Git will have to enumerate your entire filesystem (which will take a loooong time) for every 'git status', 'git add -a' or similar...

Getting that error should be impossible with GitBSLR properly installed. Sounds to me like you did not install GitBSLR properly. Perhaps your Raspberry Pi acts differently from my computers, perhaps aliases work differently on your shell, perhaps it's something else.

To narrow down the possible causes a bit, run `LD_PRELOAD=/dev/null /usr/bin/git nop` (replace /usr/bin/git if your Git is elsewhere). That should print something like 'ERROR: ld.so: object '/dev/null' from LD_PRELOAD cannot be preloaded (file too short): ignored.' (followed by git saying it doesn't know what 'nop' is).

If it doesn't, your Git is statically linked, and GitBSLR won't work.

If it does, update to the latest GitBSLR (to fix a few other issues), then use `LD_PRELOAD=/lib/gitbslr.so /usr/bin/git add /var/www/html/SITE1/user/init.php`.

If that works, your alias broke somehow. Maybe you restarted your shell between `alias git=...` and `git add ...`, maybe something else; consult your shell manual for how to debug alias-related issues.

If it does not, probably a GitBSLR bug; maybe your Git uses some function GitBSLR doesn't recognize. Run `GITBSLR_DEBUG=1 LD_PRELOAD=/lib/gitbslr.so /usr/bin/git add /var/www/html/SITE1/user/init.php` and `objdump -T /usr/bin/git`, and give me their output. This will be a few hundred lines.

**Comment by gcarabetta** [comment]
Thank you so much for your quick replay.

I tested already by myself the alias, and I got error if I not point
correctly the gitbslr.so.

I hope this contain someting interesting for you (I cannot undestand it :( )

root@raspberrypi:~# objdump -T /usr/bin/git

/usr/bin/git:     file format elf32-littlearm

DYNAMIC SYMBOL TABLE:
00000000  w   D  *UND*    00000000              _ITM_deregisterTMCloneTable
00000000  w   D  *UND*    00000000              __gmon_start__
00000000  w   D  *UND*    00000000              _Jv_RegisterClasses
00000000  w   D  *UND*    00000000              _ITM_registerTMCloneTable
00000000      DF *UND*    00000000  GLIBC_2.4   sleep
00000000      DF *UND*    00000000  GLIBC_2.4   poll
00000000      DF *UND*    00000000  GLIBC_2.4   abort
00000000      DF *UND*    00000000  GLIBC_2.4   pthread_sigmask
00000000      DF *UND*    00000000  GLIBC_2.4   getenv
00000000      DF *UND*    00000000  GLIBC_2.4   fopen64
00000000      DF *UND*    00000000  GLIBC_2.4   chdir
00000000      DF *UND*    00000000  GLIBC_2.4   localtime_r
00000000      DF *UND*    00000000  GLIBC_2.4   signal
00000000      DF *UND*    00000000  GLIBC_2.4   sysconf
00000000      DF *UND*    00000000  GLIBC_2.4   fclose
00000000      DF *UND*    00000000  GLIBC_2.4   fread
00000000      DF *UND*    00000000  GLIBC_2.4   execl
00000000      DF *UND*    00000000  GLIBC_2.4   __fprintf_chk
00000000      DF *UND*    00000000  GLIBC_2.4   bind_textdomain_codeset
00000000      DF *UND*    00000000  GLIBC_2.4   strrchr
00000000      DF *UND*    00000000  GLIBC_2.4   strchrnul
00000000      DF *UND*    00000000  GLIBC_2.4   dup
00000000      DF *UND*    00000000  GLIBC_2.4   perror
00000000      DF *UND*    00000000  GLIBC_2.4   pthread_self
00000000      DF *UND*    00000000  GLIBC_2.4   tcgetpgrp
00012be4 g    DF .init    00000000  Base        _init
00000000      DF *UND*    00000000  GLIBC_2.4   strtol
00000000      DF *UND*    00000000  GLIBC_2.4   close
00000000      DF *UND*    00000000  GLIBC_2.4   __lxstat64
00000000      DF *UND*    00000000  GLIBC_2.4   pthread_join
00000000      DF *UND*    00000000  GLIBC_2.4   setsockopt
00000000      DF *UND*    00000000  GLIBC_2.4   pthread_mutex_destroy
00000000      DF *UND*    00000000  GLIBC_2.4   _obstack_begin
00000000      DF *UND*    00000000  GLIBC_2.4   __printf_chk
00000000      DF *UND*    00000000  GLIBC_2.4   getpgid
00000000      DF *UND*    00000000  GLIBC_2.4   dcgettext
00012d90      DF *UND*    00000000  GLIBC_2.4   free
00000000      DF *UND*    00000000  GLIBC_2.4   setlocale
00000000      DF *UND*    00000000  GLIBC_2.4   fseek
00000000      DF *UND*    00000000  GLIBC_2.4   memmem
00000000      DF *UND*    00000000  GLIBC_2.4   closedir
00000000      DF *UND*    00000000  GLIBC_2.4   iconv_open
00000000      DF *UND*    00000000  GLIBC_2.4   fsync
00000000      DF *UND*    00000000  GLIBC_2.4   _IO_putc
00000000      DF *UND*    00000000  GLIBC_2.4   regfree
00000000      DF *UND*    00000000  GLIBC_2.4   flockfile
00000000      DF *UND*    00000000  GLIBC_2.4   __read_chk
00000000      DF *UND*    00000000  GLIBC_2.4   strftime
00000000      DF *UND*    00000000  GLIBC_2.4   strncmp
00000000      DF *UND*    00000000  GLIBC_2.4   pthread_cond_destroy
00000000      DF *UND*    00000000  GLIBC_2.4   strlen
00000000      DF *UND*    00000000  GLIBC_2.4   dcngettext
00000000      DF *UND*    00000000  GLIBC_2.4   malloc
001acee8 g    DO .data.rel.ro    00000004  GLIBC_2.4   __stack_chk_guard
00000000      DF *UND*    00000000  GLIBC_2.4   symlink
00000000      DF *UND*    00000000  GLIBC_2.4   __snprintf_chk
00000000      DF *UND*    00000000  GLIBC_2.4   memcmp
00000000      DF *UND*    00000000  GLIBC_2.4   clearerr
00000000      DF *UND*    00000000  GLIBC_2.4   pthread_mutexattr_init
00000000      DF *UND*    00000000  GLIBC_2.4   __assert_fail
00000000      DF *UND*    00000000              deflateInit_
00000000      DF *UND*    00000000              pcre_study
00000000      DF *UND*    00000000  GLIBC_2.4   tcsetattr
00000000      DF *UND*    00000000              inflateInit2_
00000000      DF *UND*    00000000  GLIBC_2.4   pthread_key_create
00000000      DF *UND*    00000000  GLIBC_2.4   mkdir
00000000      DF *UND*    00000000              crc32
00000000      DF *UND*    00000000  GLIBC_2.4   __memcpy_chk
00000000      DF *UND*    00000000              inflate
00000000      DF *UND*    00000000  GLIBC_2.4   strcasestr
00000000      DF *UND*    00000000  GLIBC_2.4   regerror
00000000      DF *UND*    00000000  GLIBC_2.4   strpbrk
00000000      DF *UND*    00000000  GLIBC_2.4   ferror
00000000      DF *UND*    00000000  GLIBC_2.4   sigaddset
00000000      DF *UND*    00000000  GLIBC_2.4   dirname
00000000      DF *UND*    00000000  GLIBC_2.4   getcwd
00000000      DF *UND*    00000000  GLIBC_2.4   setenv
00000000      DF *UND*    00000000  GLIBC_2.4   __xpg_basename
00000000      DF *UND*    00000000  GLIBC_2.4   putenv
00000000      DF *UND*    00000000  GLIBC_2.4   freeaddrinfo
00000000      DF *UND*    00000000  GLIBC_2.4   memset
00000000      DF *UND*    00000000  GLIBC_2.4   putchar
00000000      DF *UND*    00000000  GLIBC_2.4   ftruncate64
00000000      DF *UND*    00000000  GLIBC_2.4   readdir64
00000000      DF *UND*    00000000  GLIBC_2.4   fileno
00000000      DF *UND*    00000000  GLIBC_2.4   unsetenv
00000000      DF *UND*    00000000              pcre_exec
00000000      DF *UND*    00000000  GLIBC_2.4   strtoul
00000000      DF *UND*    00000000  GLIBC_2.4   munmap
00000000      DF *UND*    00000000  GLIBC_2.4   clock_gettime
00000000      DF *UND*    00000000  GLIBC_2.4   __ctype_b_loc
00000000      DF *UND*    00000000  GLIBC_2.4   gethostname
00147868 g    DF .text    00000064  Base        error
00000000      DF *UND*    00000000  GLIBC_2.4   pthread_key_delete
00000000      DF *UND*    00000000  GLIBC_2.4   getnameinfo
00000000      DF *UND*    00000000  GLIBC_2.4   pthread_mutexattr_destroy
00000000      DF *UND*    00000000  GLIBC_2.4   memchr
00000000      DF *UND*    00000000  GLIBC_2.4   fdopen
00000000      DF *UND*    00000000              inflateInit_
00000000      DF *UND*    00000000  GLIBC_2.4   umask
00000000      DF *UND*    00000000  GLIBC_2.4   __strtoll_internal
00000000      DF *UND*    00000000  GLIBC_2.4   pthread_cond_signal
00000000      DF *UND*    00000000  GLIBC_2.4   strstr
00000000      DF *UND*    00000000  GLIBC_2.4   getpagesize
00000000      DF *UND*    00000000  GLIBC_2.4   pthread_mutex_unlock
00000000      DF *UND*    00000000  GLIBC_2.4   pipe
00000000      DF *UND*    00000000  GLIBC_2.4   pthread_getspecific
00000000      DF *UND*    00000000  GLIBC_2.4   execvp
00000000      DF *UND*    00000000  GLIBC_2.4   link
00000000      DF *UND*    00000000  GLIBC_2.4   pthread_cond_init
00000000      DF *UND*    00000000  GLIBC_2.4   fscanf
00000000      DF *UND*    00000000  GLIBC_2.4   dup2
00000000      DF *UND*    00000000  GLIBC_2.4   __stack_chk_fail
00000000      DF *UND*    00000000  GLIBC_2.4   __fxstat64
00000000      DF *UND*    00000000  GLIBC_2.4   readlink
00000000      DF *UND*    00000000  GLIBC_2.4   localtime
001b21b0 g    DO .bss    00000004  GLIBC_2.4   stdin
00000000      DF *UND*    00000000  GLIBC_2.4   pthread_cond_broadcast
001b21a8 g    D  .data    00000000  Base        _edata
00000000      DF *UND*    00000000  GLIBC_2.4   calloc
00000000      DF *UND*    00000000  GLIBC_2.4   pthread_cond_wait
00000000      DF *UND*    00000000  GLIBC_2.4   strcspn
00000000      DF *UND*    00000000  GLIBC_2.4   getuid
00000000      DF *UND*    00000000  GLIBC_2.4   gmtime_r
00000000      DF *UND*    00000000  GLIBC_2.4   puts
00000000      DF *UND*    00000000  GLIBC_2.4   __memset_chk
00000000      DF *UND*    00000000  GLIBC_2.4   pthread_mutex_lock
00000000      DF *UND*    00000000  GLIBC_2.4   sigaction
00000000      DF *UND*    00000000  GLIBC_2.4   ungetc
00000000      DF *UND*    00000000  GLIBC_2.4   _obstack_newchunk
00000000      DF *UND*    00000000  GLIBC_2.4   utime
00000000      DF *UND*    00000000              deflate
00000000      DF *UND*    00000000  GLIBC_2.4   getdelim
00000000      DF *UND*    00000000  GLIBC_2.4   __libc_start_main
00000000      DF *UND*    00000000  GLIBC_2.4   fgetc
00000000      DF *UND*    00000000  GLIBC_2.4   obstack_free
00000000      DF *UND*    00000000              pcre_maketables
00000000      DF *UND*    00000000  GLIBC_2.4   shutdown
00000000      DF *UND*    00000000  GLIBC_2.4   strerror
001b21b4 g    DO .bss    00000004  GLIBC_2.4   stdout
00000000      DF *UND*    00000000  GLIBC_2.4   qsort
00000000      DF *UND*    00000000  GLIBC_2.4   fwrite
00000000      DF *UND*    00000000  GLIBC_2.4   opendir
00000000      DF *UND*    00000000  GLIBC_2.4   pthread_setspecific
00000000      DF *UND*    00000000  GLIBC_2.4   connect
00000000      DF *UND*    00000000  GLIBC_2.4   gmtime
00000000      DF *UND*    00000000  GLIBC_2.4   time
00000000      DF *UND*    00000000  GLIBC_2.4   getrlimit64
00000000      DF *UND*    00000000  GLIBC_2.4   waitpid
00000000      DF *UND*    00000000  GLIBC_2.4   rename
00000000      DF *UND*    00000000  GLIBC_2.4   exit
00000000      DF *UND*    00000000  GLIBC_2.4   sscanf
00000000      DF *UND*    00000000  GLIBC_2.4   ioctl
001b21b8 g    DO .bss    00000004              pcre_free
00000000      DF *UND*    00000000  GLIBC_2.4   rmdir
00000000      DF *UND*    00000000  GLIBC_2.4   fgets
00000000      DF *UND*    00000000  GLIBC_2.4   lseek64
00000000      DF *UND*    00000000  GLIBC_2.4   read
00000000      DF *UND*    00000000  GLIBC_2.7   __fread_chk
001f446c g    D  .bss    00000000  Base        __end__
00000000      DF *UND*    00000000  GLIBC_2.4   chmod
00000000      DF *UND*    00000000  GLIBC_2.4   iconv_close
00000000      DF *UND*    00000000  GLIBC_2.4   fcntl
00000000      DF *UND*    00000000  GLIBC_2.4   getpwuid
00000000      DF *UND*    00000000  GLIBC_2.4   strcasecmp
00000000      DF *UND*    00000000  GLIBC_2.4   freopen64
00000000      DF *UND*    00000000  GLIBC_2.4   write
00000000      DF *UND*    00000000  GLIBC_2.4   getpwnam
00000000      DF *UND*    00000000  GLIBC_2.4   nl_langinfo
00000000      DF *UND*    00000000  ZLIB_1.2.0  deflateBound
00000000      DF *UND*    00000000  GLIBC_2.4   __vfprintf_chk
00000000      DF *UND*    00000000  GLIBC_2.4   kill
00000000      DF *UND*    00000000  GLIBC_2.4   textdomain
00000000      DF *UND*    00000000  GLIBC_2.4   mktime
00000000      DF *UND*    00000000  GLIBC_2.4   __errno_location
00000000      DF *UND*    00000000  GLIBC_2.4   rand
00000000      DF *UND*    00000000  GLIBC_2.4   sigprocmask
00000000      DF *UND*    00000000  GLIBC_2.4   open64
00000000      DF *UND*    00000000  GLIBC_2.4   regcomp
00000000      DF *UND*    00000000              deflateInit2_
00000000      DF *UND*    00000000              pcre_compile
00000000      DF *UND*    00000000  GLIBC_2.4   bindtextdomain
00000000      DF *UND*    00000000  GLIBC_2.4   strspn
00000000      DF *UND*    00000000  GLIBC_2.4   gai_strerror
00000000      DF *UND*    00000000  GLIBC_2.4   __strtoull_internal
00000000      DF *UND*    00000000  GLIBC_2.4   mmap64
00000000      DF *UND*    00000000  GLIBC_2.4   ftell
00000000      DF *UND*    00000000  GLIBC_2.4   isatty
00000000      DF *UND*    00000000  GLIBC_2.4   fork
00000000      DF *UND*    00000000  GLIBC_2.4   pthread_exit
00000000      DF *UND*    00000000  GLIBC_2.4   execlp
00000000      DF *UND*    00000000  GLIBC_2.4   __cxa_atexit
00000000      DF *UND*    00000000              deflateEnd
00000000      DF *UND*    00000000  GLIBC_2.4   memcpy
00000000      DF *UND*    00000000  GLIBC_2.4   realloc
00000000      DF *UND*    00000000  GLIBC_2.4   pthread_create
00000000      DF *UND*    00000000  GLIBC_2.4   __uflow
00000000      DF *UND*    00000000  GLIBC_2.4   pthread_mutex_init
00000000      DF *UND*    00000000  GLIBC_2.4   unlink
00012cac      DF *UND*    00000000  GLIBC_2.4   strcmp
00000000      DF *UND*    00000000  GLIBC_2.4   uname
001b21a8 g    DO .bss    00000004  GLIBC_2.4   stderr
00000000      DF *UND*    00000000  GLIBC_2.4   setsid
001b21a8 g    D  .bss    00000000  Base        __bss_start
00000000      DF *UND*    00000000  GLIBC_2.4   fputc
001b21a8 g    D  .bss    00000000  Base        __bss_start__
00000000      DF *UND*    00000000  GLIBC_2.4   pthread_mutexattr_settype
00000000      DF *UND*    00000000  GLIBC_2.4   gettimeofday
001f446c g    D  .bss    00000000  Base        _end
00000000      DF *UND*    00000000  GLIBC_2.4   raise
00000000      DF *UND*    00000000  GLIBC_2.4   __vsnprintf_chk
00000000      DF *UND*    00000000  GLIBC_2.4   srand
00000000      DF *UND*    00000000  GLIBC_2.4   mkdtemp
00000000      DF *UND*    00000000  GLIBC_2.4   memmove
00000000      DF *UND*    00000000  GLIBC_2.4   getpid
00000000      DF *UND*    00000000  GLIBC_2.4   socket
00000000      DF *UND*    00000000  GLIBC_2.4   setvbuf
00000000      DF *UND*    00000000  GLIBC_2.4   __strdup
00000000      DF *UND*    00000000  GLIBC_2.4   __xstat64
001f446c g    D  .bss    00000000  Base        _bss_end__
00000000      DF *UND*    00000000  GLIBC_2.4   pread64
00000000      DF *UND*    00000000  GLIBC_2.4   fputs
00000000      DF *UND*    00000000  GLIBC_2.4   mkstemp64
00000000      DF *UND*    00000000  GLIBC_2.7   __open64_2
00000000      DF *UND*    00000000  GLIBC_2.4   fflush
00000000      DF *UND*    00000000  GLIBC_2.4   regexec
00000000      DF *UND*    00000000  GLIBC_2.4   strncasecmp
001f446c g    D  .bss    00000000  Base        __bss_end__
00000000      DF *UND*    00000000  GLIBC_2.4   access
00000000      DF *UND*    00000000  GLIBC_2.4   getaddrinfo
00000000      DF *UND*    00000000  GLIBC_2.4   funlockfile
00000000      DF *UND*    00000000  GLIBC_2.4   feof
00000000      DF *UND*    00000000  GLIBC_2.4   sigemptyset
00000000      DF *UND*    00000000  GLIBC_2.4   setitimer
0015f2a0 g    DF .fini    00000000  Base        _fini
00000000      DF *UND*    00000000  GLIBC_2.4   iconv
00000000      DF *UND*    00000000  GLIBC_2.4   __memmove_chk
00000000      DF *UND*    00000000              inflateEnd
00000000      DF *UND*    00000000  GLIBC_2.4   strchr
00000000      DF *UND*    00000000  GLIBC_2.4   tcgetattr


root@raspberrypi:~#

Let me know :)

Giulio

Il giorno gio 21 giu 2018 alle ore 18:51 Alcaro <notifications@github.com>
ha scritto:

**Comment by gcarabetta** [comment]
Sorry, I lost this:
root@raspberrypi:~# GITBSLR_DEBUG=1 LD_PRELOAD=/lib/gitbslr.so /usr/bin/git
add /var/www/html/users/init.php
fatal: pathspec '/var/www/html/users/init.php' is beyond a symbolic link
root@raspberrypi:~#

It seems to not use the DEBUG var...

But, to confirm other aspect:

root@raspberrypi:~# LD_PRELOAD=/dev/null /usr/bin/git nop
ERROR: ld.so: object '/dev/null' from LD_PRELOAD cannot be preloaded (file
too short): ignored.
git: 'nop' is not a git command. See 'git --help'.

Did you mean one of these?
    clone
    log
    notes
root@raspberrypi:~#



Il giorno gio 21 giu 2018 alle ore 18:51 Alcaro <notifications@github.com>
ha scritto:

**Comment by Alcaro** [comment]
Nothing interesting in that objdump blob, GitBSLR is already overriding everything it should.

Yes, it seems to not use the debug variable. Or the LD_PRELOAD variable at all, except /dev/null does complain... you did install the latest GitBSLR, right? I added the debug variable just a few hours ago. To verify, 'grep GITBSLR_DEBUG /lib/gitbslr.so'; if binary file does not match, you're outdated.

If the binary file does match, `LD_PRELOAD=/dev/null /usr/bin/git nop` says file too short, and `GITBSLR_DEBUG=1 LD_PRELOAD=/lib/gitbslr.so /usr/bin/git nop` does not print 'GitBSLR: loaded', then I can only conclude that something on your system is broken, and that it's not GitBSLR.

**Comment by gcarabetta** [comment]
Effectively I got (fro few minutes) the old version :)

Now, with the fresh, Iget this debug:

root@raspberrypi:~/1/GitBSLR-master# GITBSLR_DEBUG=1
LD_PRELOAD=/lib/gitbslr.so /usr/bin/git add /var/www/html/users/init.php
GitBSLR: loaded
GitBSLR: chdir(..)
GitBSLR: chdir(..)
GitBSLR: chdir(..)
GitBSLR: __lxstat64(.git/HEAD)
GitBSLR: chdir(.)
GitBSLR: __lxstat64(/)
GitBSLR: chdir(/)
GitBSLR: chdir(.git)
GitBSLR: __lxstat64(/.git)
GitBSLR: chdir(/)
GitBSLR: chdir(/)
GitBSLR: readlink(.git/index)
GitBSLR: __lxstat64(var)
GitBSLR: __lxstat64(var/www)
GitBSLR: __lxstat64(var/www/html) -> html.4.2.24
fatal: pathspec '/var/www/html/users/init.php' is beyond a symbolic link




Il giorno gio 21 giu 2018 alle ore 21:14 Alcaro <notifications@github.com>
ha scritto:

**Comment by Alcaro** [comment]
...oh right, now I get it.

Since symlinks to inside the repo work on others' computers too, GitBSLR keeps them around.

But yes, that should be configurable (though I think it could cause explosive numbers of duplicate files depending on how your symlinks are configured...).

I'll fix it at some point; until then, add '/var/www/html' and '/var/www/html.4.2.24/users/init.php' to the repo (this works both with and without GitBSLR).

**Comment by Alcaro** [comment]
Implemented in-repo symlink inlining as of https://github.com/Alcaro/GitBSLR/commit/65367549ccabf0609214bf622aa9c476195dff4d.

As for epcim's original issue, I'll assume my workaround is good enough. If not, create a new issue, discussing two issues in the same GitHub issue is kinda messy.
