### ISSUE TITLE
Put gitbslr.so in ~/bin

### ISSUE THREAD

**Issue by blakemcbride** [Alcaro/GitBSLR#3]
Greetings, and thanks for a great solution!

Looking at your install script, I have a preference that I thought I'd share.  I'd prefer that the install script put gitbslr.so into ~/bin and use that one.  This way the install script truly "installs" it.  Otherwise, I am unknowingly dependent on the existence and contents of my build directory.

**Comment by Alcaro** [comment]
A counterargument would be that ~/bin/ should contain executables only.

But there's no other good place for this thing. ~/bin/ is better than the repo, and it's easy to edit ~/bin/git if needed. So yes, this would be an improvement.
