### ISSUE TITLE
Needless delarations

### ISSUE THREAD

**Issue by blakemcbride** [Alcaro/GitBSLR#5]
Hi.  I'm not a C++ expert, but I am a C expert.  You have several lines like this:

    DLLEXPORT int chdir(const char * path);
    DLLEXPORT int chdir(const char * path)

There is no need for the first, declaration, line.  As long as the function isn't used before that place in the file, the function definition also serves as a function declaration.  Of course, if you did use the function earlier in the file, the declaration would also have to appear earlier.  That's when declarations are needed.

**Comment by Alcaro** [comment]
I compile with -Wmissing-declarations, and last time I checked, that warning was triggered if I removed the seemingly-pointless declaration.

But apparently something has changed since said last check, so they are indeed no longer needed.
