### ISSUE TITLE
Coding style recommendation

### ISSUE THREAD

**Issue by blakemcbride** [Alcaro/GitBSLR#6]
Greetings,

I hope this can be taken with the respect it is offered.  I have been programming in C for about 30 years.  I'd like to make one small suggestion.  Lines like the following:

    if (ret<0 || !initialized) return ret;

are a problem because you can't set a breakpoint on the return.  If, however, it were written as follows:

    if (ret<0 || !initialized)
        return ret;

You'd have the ability to break at the 'if' or the consequence of the 'if'.  So basically I am saying that one should never put an 'if' statement and its consequence on the same line.

Just sharing my experience.  Thanks!

**Comment by Alcaro** [comment]
Ah yes, coding style, the one thing nobody ever agrees on.

Yes, more linebreaks makes the debugger happier.

But I've never considered that an issue. In all code I've had a reason to debug, I've been able to easily edit the source to add more breakpoint opportunities. If that option is unavailable, I'd identify which assembly instructions correspond to the return and breakpoint that, or make the breakpoint conditional.

That said, perhaps your conclusion is correct anyways. While I prefer keeping my code reasonably compact, my preferences have changed many times, usually towards more whitespace.

Perhaps it's time for them to change again. Thanks for your suggestion.

e: if I do decide to change, I'll edit GitBSLR - and all my other code - once I find the outdatedly-formatted code. Until then, there's nothing about this particular formatting change that needs an open issue.
