### ISSUE TITLE
Symlinks still list as untracked files.

### ISSUE THREAD

**Issue by snippins** [Alcaro/GitBSLR#8]
While `git status` behaves correctly, the following command, which finds untracked files, shows all the symlinks to directories.

`git ls-files --others --exclude-standard`

**Comment by Alcaro** [comment]
```
Initialized empty Git repository in /home/alcaro/gitest/.git/
alcaro@stacked:~/gitest$ mkdir a
alcaro@stacked:~/gitest$ ln -s a ln-a
alcaro@stacked:~/gitest$ echo aa > a/b
alcaro@stacked:~/gitest$ git add a/b
alcaro@stacked:~/gitest$ git ls-files --others --exclude-standard
ln-a/b
```
Yeah, that's a bug. If ln-a points to within the repo, it should be treated as a link.

Will fix.

**Comment by Alcaro** [comment]
note to self: don't run git commands in ~. Pretty impressive error, though. `warning: could not open directory '.wine/dosdevices/z:/tmp/systemd-private-1a32e8755ce84f869b62c14aba334889-systemd-timesyncd.service-H1IL8g/': Permission denied`

This was way harder than I expected to fix, but I think I solved it. Thanks for the report.
