### ISSUE TITLE
Rename to README.md

### ISSUE THREAD

**Issue by YodaEmbedding** [Alcaro/GitBSLR#9]
If you rename the README to have the file-extension `.md`, the text on the repo's homepage becomes more readable. (You'll also need to change the list to use `1.`, `2.`, `3.`, ... to ensure numbered bullets.)

**Comment by Alcaro** [comment]
Word-wrapped md looks silly, and non-wrapped is slightly harder to edit.

But this repo is intended to be used, not my personal toy, so let's just go with md.
